// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'puedes ejecutar FlutterFire CLI nuevamente si necesitas esta plataforma.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSudiIhNiDce03z-SN0mhfNSLIfuNlX_s',
    appId: '1:579194189083:web:428b6084d29400dea8cfbe',
    messagingSenderId: '579194189083',
    projectId: 'examenfinal-261ac',
    authDomain: 'examenfinal-261ac.firebaseapp.com',
    storageBucket: 'examenfinal-261ac.firebasestorage.app',
    measurementId: 'G-ZHPCL1HY38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgUBqktAZWQwB_fxUngTFQ9JiPKtRlBb8',
    appId: '1:579194189083:android:c90f4ca1a1b6ef14a8cfbe',
    messagingSenderId: '579194189083',
    projectId: 'examenfinal-261ac',
    storageBucket: 'examenfinal-261ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTFE3AD-VLj13i-k0IaidYvtX3o_0vaw',
    appId: '1:579194189083:ios:25096d11d7226a0aa8cfbe',
    messagingSenderId: '579194189083',
    projectId: 'examenfinal-261ac',
    storageBucket: 'examenfinal-261ac.firebasestorage.app',
    iosBundleId: 'com.example.examenfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKTFE3AD-VLj13i-k0IaidYvtX3o_0vaw',
    appId: '1:579194189083:ios:25096d11d7226a0aa8cfbe',
    messagingSenderId: '579194189083',
    projectId: 'examenfinal-261ac',
    storageBucket: 'examenfinal-261ac.firebasestorage.app',
    iosBundleId: 'com.example.examenfinal',
  );

  // Windows no configurado.
}